# Docker Compose build file: docker-compose -f build.yml build
version: "3.7"

x-common-args: &common-args
  PIHOLE_VERSION: ${PIHOLE_VERSION}
  NAME: jdopson/pihole
  MAINTAINER: jdopson@gmail.com
  S6_VERSION: v1.22.1.0
  PHP_ENV_CONFIG: /etc/lighttpd/conf-enabled/15-fastcgi-php.conf
  PHP_ERROR_LOG: /var/log/lighttpd/error.log


services:
  amd64:
    image: jdopson/pihole:${PIHOLE_VERSION}-amd64
    build:
      context: .
      args:
        <<: *common-args
        PIHOLE_BASE: pihole/debian-base:${DEBIAN_VERSION:-stretch}
        PIHOLE_ARCH: amd64
        S6_ARCH: amd64
